name: river_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  random_name_generator: ^1.2.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
